### ISSUE TITLE
Не работает скачивание Манги вот скрншот

### ISSUE THREAD

**Issue by Zack95** [AcidBear/mngDownloader#1]
<img width="489" alt="2017-05-13 0 08 37" src="https://cloud.githubusercontent.com/assets/22136377/26017087/8c6dd932-3770-11e7-8bc3-1ad06fc603c3.png">

**Comment by AcidBear** [comment]
Проблема была в алгоритме поиска картинок. Сейчас всё должно работать. Благодарю за баг-репорт.
