### ISSUE TITLE
MintManga выдаёт ошибку "У Вас отключен JavaScript. Чтение манги невозможно." при скачивании манги

### ISSUE THREAD

**Issue by Zack95** [AcidBear/mngDownloader#13]
Не качается манга конкретно вот эта http://mintmanga.com/soft_boiled_girls
С другими проблем не видел. 
<img width="1557" alt="2018-12-20 0 32 49" src="https://user-images.githubusercontent.com/22136377/50249452-27b8cb80-03ef-11e9-881d-03cb6287cb32.png">

**Comment by Zack95** [comment]
Прости что беспокою. А есть надежда на починку этого бага ?

**Comment by AcidBear** [comment]
@Zack95, хочется переписать этот скрипт, но пока что времени на это не очень хватает. Сорре.

**Comment by AcidBear** [comment]
На всякий случай: чтобы исправить баг, придётся переписать чуть ли не весь код, связанный с закачкой. Так что, по сути, скрипт превратился в неподдерживаемую кучу кода, в которой, если и можно разобраться, то придётся приложить неплохие усилия.

Так что я решил сделать новую, более простую программу, которая хотя бы по своей задумке будет более гибкой и менее завязанной на, кхм... специфические решения.

**Comment by Zack95** [comment]
Буду ждать новый )
За глупый форк прости. Хотел дописать и сам поддерживать но забросил и забыл удалить форк. Исправил.

**Comment by AcidBear** [comment]
@Zack95 так то её репозиторий находится здесь:
https://notabug.org/jakeSlaz/nmanga

Но она пока в нерабочем состоянии находится. Прасинг ссылок есть, но загрузку ещё не допилил.
