### ISSUE TITLE
Уход с GitHub'a

### ISSUE THREAD

**Issue by AcidBear** [AcidBear/mngDownloader#14]
GitHub недавно намеренно поломал свою работоспособность на т.н. "неподдерживаемых" браузеров и теперь я здесь не могу нормально работать: редактировать "Issues", смотреть последние коммиты и прочее, что довольно критично для меня.

И нужно смотреть в сторону альтернативных платформ.

**Comment by AcidBear** [comment]
Я даже не могу отредактировать пост выше, чтобы он читался нормально. Это очень сильно напрягает.

Из всех альтернатив более-менее адекватным я нахожу GNU Savannah (savannah.nongnu.org), но там относительно высоковатый порог вхождения, т.к. требуется предварительная регистрация проекта с премодерацией сорцов и предварительная их подготовка на предмет, к примеру, правильно расставленных копирайтов и прочее.

**Comment by Zack95** [comment]
А эти варианты нам не подходят ? https://bitbucket.org и https://about.gitlab.com ???
Прошу прошения а что это за браузеры попали в список не поддерживаемых ?

**Comment by AcidBear** [comment]
> А эти варианты нам не подходят ? https://bitbucket.org и https://about.gitlab.com ???

Мне не нравится в них то, что они довольно сильно обмазаны javascript'ом. Боюсь, что через некоторое время они пойдут по пути GitHub'а.

Саванна в этом плане же кажется довольно стабильной.

> а что это за браузеры попали в список не поддерживаемых ?

Ну, например, firefox-52.7.3. Раньше всё отлично работало, но теперь тот же функционал резко перестал работать. Очень странная вешь. И не у меня одного, что характерно.

**Comment by AcidBear** [comment]
Интересный момент: если в моём браузере выставить юзерагент "поддерживаемого" браузера, то весь функционал внезапно возвращается. То бишь, ГитХаб тупо угнетает неугодные браузеры, не давая им полноценно работать на этой площадке.

Я считаю, что это очень плохая практика, и что с таких площадок, которые её используют нужно бежать как можно скорее.

**Comment by Zack95** [comment]
Вообще не очень ситуация. Но они JS вроде как для безопасности. Кстати а почему firefox на 63 не обновишь ? или тебе квантам не нравиться ?

**Comment by AcidBear** [comment]
> Кстати а почему firefox на 63 не обновишь ?

https://www.opennet.ru/opennews/art.shtml?num=47328
Mozilla полностью ломает мне мой workflow своими обновлениями. А учитывая, что я и так не очень люблю firefox, то тут остаётся только 2 вещи: либо продолжать пользоваться 52-ESR, либо найти что-то другое, чем я сейчас и занимаюсь.
