### ISSUE TITLE
перестала запускаться не видит файл конфигурации 

### ISSUE THREAD

**Issue by Zack95** [AcidBear/mngDownloader#2]
<img width="1373" alt="2017-05-14 21 50 07" src="https://cloud.githubusercontent.com/assets/22136377/26036890/866c1b22-38ef-11e7-836d-08fdf18847f9.png">

**Comment by AcidBear** [comment]
У меня всё работает. Попробуйте сделать в директории программы следующие шаги:
```sh
$ git fetch --all
$ git reset --hard origin/master
```
Это должно сбросить все файлы, которые есть в данной папке (в том числе и файл конфигурации), до состояния в точности как в этом репозитории.

Если это не помогло, то отправьте вывод консоли в момент ошибки.

**Comment by AcidBear** [comment]
Вы запускаете программу с помощью абсолютного пути. Попробуйте запустить прграмму из её директории, войдя в неё. Например так:
```sh
cd /Users/ilya/Downloads/mngDownloader-master/console.py
python3 console.py
```
Если вы не хотите так делать, то можете с помощью аргументов к программе указать путь к файлу конфигурации, который находится в папке с программой:
```sh
python3 /Users/ilya/Downloads/mngDownloader-master/console.py --config_path=/Users/ilya/Downloads/mngDownloader-master/config.toml
```

P.S. И да, в следующий раз лучше выкладвыайте вывод консоли в текстовом виде. Про то, как его оформить, сказано [здесь](https://github.com/OlgaVlasova/markdown-doc/blob/master/README.md#Code) (раздел "Кодовые фрагменты строк").
