### ISSUE TITLE
Вопрос

### ISSUE THREAD

**Issue by Zack95** [AcidBear/mngDownloader#4]
Привет скажи как ты сумел создать json с ссылками на всю мангу ?

**Comment by AcidBear** [comment]
Всмысле как сгенерировал его? С помощью парсера (parser.py), который находится в modules/parser в этом репозитории.

**Comment by Zack95** [comment]
то есть запустив его я могу создать новый json обновленный если вдруг он устарел ? 
И еще такой вопрос может ты вкурсе как получить все станицы сайта (sitemap)? Нужно найти вхождение в коде всех станиц чужого сайта. (на ум приходит только парсинг станиц и переход по ссылкам в ней и так далее до конца)

**Comment by AcidBear** [comment]
>то есть запустив его я могу создать новый json обновленный если вдруг он устарел ?

По идее. Правда, я его давно не обновлял.

>sitemap

Впервые слышу о таком слове, лол. Но небольшой гуглёж показывает вот это насчёт Ридманги: http://readmanga.me/sitemap.xml

>Нужно найти вхождение в коде всех станиц чужого сайта.

Извини, но немного не понял тебя.

>на ум приходит только парсинг станиц и переход по ссылкам в ней и так далее до конца

Ну, парсинг Ридманги у меня, в принципе, так и реализован. Просто листает страницы, собирая названия манги со ссылками. И так до конца (конечного значения, указанного в парсере). Топорно, но работает.

**Comment by Zack95** [comment]
Запустил парсер ругается на отсутствие файла хотя файл есть 
<img width="685" alt="2017-05-16 17 55 37" src="https://cloud.githubusercontent.com/assets/22136377/26112609/1222cb08-3a61-11e7-9335-3d359d857e5a.png">

**Comment by AcidBear** [comment]
Там надо аргумент указать. `readmanga`, `mintmanga` или `mangareader`.

**Comment by Zack95** [comment]
а я - перед аргументами ставил. Если ты не против я допишу в течение недели в интерфейс обновление этих баз. Что бы любой спокойно мог. И еще вопрос есть ли смысл держать mangareader он еще актуален и с него качают и читают ?

**Comment by AcidBear** [comment]
> Если ты не против я допишу в течение недели в интерфейс обновление этих баз.  Что бы любой спокойно мог.

Чтобы любой спокойно мог что? Делать лишнюю нагрузку на сервера Ридманги? Не нужно. Если человеку нужно скачать мангу, которой нет в базах, то он может либо запросить обновление баз (чтобы потом их любой мог скачать), либо обновить их вручную, либо ввести полную ссылку на мангу прямо в загрузчик с помощью команды `--full-link`. Как видишь, варианты и без этого есть.

>  И еще вопрос есть ли смысл держать mangareader

Mangareader, всмысле, как его поддержка загрузчиком? Так он и не поддерживается. Я начинал ради прикола его писать... Начинал. Ну, это и осталось начинанием, потому что я не читаю анлейт и, впринципе, его поддержка мне не очень требовалась.

> он еще актуален?

Мангаридер (сайт), вроде как, недавно обновился, так что хз.

> с него качают и читают?

Нет. Потому что загрузчик его не поддерживает.

У меня есть мысль выкинуть любое упоминание о мангаридере с master-ветки в какую-нибудь devel-ветку. А когда его поддержка будет сделана и работать, вернуть обратно в master-ветку.

**Comment by Zack95** [comment]
Тут после скачивания Манги в 200+ глав случился такой вот глюк 
<img width="491" alt="2017-07-07 14 52 35" src="https://user-images.githubusercontent.com/22136377/27956846-420bacea-6324-11e7-8dd2-b9bbb739ab7d.png">

**Comment by AcidBear** [comment]
Походу Минтманга обновилась. Потребуется некоторое время на обновление алгоритма поиска изображений. Я отпишу, когда оно обратно заработает. Спасибо за репорт.

P.S.: Желательно для таких проблем заводить отдельный issue. И ещё лучше уточнять, что проблема при скачивании с Ридманги/Минтманги, чтобы я быстрее мог находить проблемы. Алгоритмы там разные и по-разному работают.

**Comment by AcidBear** [comment]
Вроде исправлено.
