### ISSUE TITLE
Большая манга не качается 

### ISSUE THREAD

**Issue by Zack95** [AcidBear/mngDownloader#5]
качаю вот эту мангу 
http://mintmanga.com/my_girlfriend_is_a_virgin_who_takes_being_slutty_too_seriously

и на 15 главе все сломалось перезапуск не помогает вообще при попытке скачать что угодно пишет  туже ошибку прикладываю 2 скриншота со всеми командами 
<img width="380" alt="2017-07-26 21 26 33" src="https://user-images.githubusercontent.com/22136377/28637163-45f68df0-7249-11e7-8f63-0f43d91d53c8.png">
<img width="926" alt="2017-07-26 21 26 47" src="https://user-images.githubusercontent.com/22136377/28637166-48733416-7249-11e7-93e8-b89824f9c8fc.png">

**Comment by AcidBear** [comment]
mngDownloader довольно плохо работает с экстра-главами. А ошибка здесь возникает именно при её скачивании. Можно попробовать как временное решение скачать все главы, кроме 15-ой, а потом скачать экстру, указав главу как `1/15`, что означает скачивание 15-й главы первого тома, чем и является эта экстра на МинтМанге. 

Можно ещё поступить по-другому и разрешить разбиение манги на тома.

Но больше всего меня озадачивает то, что ты написал, что после этого ломается скачивание и другой манги с той же ошибкой. Я пока не могу попробовать воспроизвести этот момент, так что было бы неплохо, если бы ты привёл логи (ну, или скрины) этого. Важно, чтобы у этой манги не было экстра-глав.

**Comment by Zack95** [comment]
Да я посмотрел в других мангах которые я пытаюсь качать тоже есть экстра главы и на этом и ломаются. Пробовал разбивать мангу на тома но не помогает. 
<img width="694" alt="2017-08-01 16 52 20" src="https://user-images.githubusercontent.com/22136377/28828622-ec4e2674-76d9-11e7-894d-62c421a9bdda.png">

**Comment by AcidBear** [comment]
В общем, нужно сделать обнаружение экстра-глав, и я приблизительно знаю как это можно сделать. Попробую заняться этим в ближайшие дни.

**Comment by AcidBear** [comment]
Добавил обработку экстра-глав. Баг всё ещё не исправлен, но теперь можно без ошибок скачать мангу, если не разбивать её на тома.

Также нужно обновить базу ссылок на мангу, т.к. некоторые из них уже устарели. Например, на эту мангу: http://mintmanga.com/my_girlfriend_is_a_faithful_virgin_bitch

**Comment by AcidBear** [comment]
Исправлено.
