### ISSUE TITLE
Исправить скачивание глав с одинаковыми номерами, но разными томами

### ISSUE THREAD

**Issue by fodrice** [AcidBear/mngDownloader#8]
http://readmanga.me/he_is_a_high_school_girl/
У меня вылеты при скачке этой манги. (когда качал всю). Там номера томов в екстрах идут с повторами, или что-то вроде того.
И еще, не мог бы ты добавить диапазон глав для скачивания

**Comment by AcidBear** [comment]
Удивитилельно, что этот скрипт всё ещё работает, хотя я к нему около года уже не притрагивался. Посмотрю на днях.

Диапазон для глав, вроде бы, есть, но он сейчас почему-то поломан.

**Comment by AcidBear** [comment]
> Там номера томов в екстрах идут с повторами, или что-то вроде того.
Да там есть одинаковые номера глав с разными томами. Известная проблема для этого загрузчика. Пока можно обходить это с помощью диапазонов и указывания конкрентных томов, типа:
`3/61`
`4/61`
`62-81`

**Comment by AcidBear** [comment]
Лог ошибки:
```sh
He is a High School Girl, глава 62...
4/4 [####################][ COMPLETE ]
He is a High School Girl, глава 61...
Traceback (most recent call last):ADING ]
  File "./console.py", line 410, in <module>
    image_number)
  File "/home/rusty/code/mngDownloader/modules/downloader/manga.py", line 59, in downloadChapterImage
    download_link = chapter.getImageLink(image_number)
  File "/home/rusty/code/mngDownloader/modules/downloader/chapters.py", line 31, in getImageLink
    return self.images['links'][image_number]
IndexError: list index out of range
```
